# Generated by Django 3.1.7 on 2021-06-26 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('delete_object', 'User delete object'), ('create_object', 'User create object'), ('edit_object', 'User edit object')], default='edit_object', max_length=20, verbose_name='action')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('description', models.CharField(max_length=120)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Action log',
                'verbose_name_plural': 'Actions log',
                'ordering': ['-date'],
            },
        ),
    ]
